"""Log de conversación: vuelca el texto del asistente a events.db.

La reflexión nocturna (services/reflection/reflect.py) consume los kinds
'user_said' y 'assistant_said' de /logs/events.db. El lado del usuario lo
escribe TranscriptWatcher (security.py); este procesador cubre el lado del
asistente. Se coloca en el pipeline entre el LLM y el TTS.

Frames verificados contra pipecat v1.3.0 (src/pipecat/frames/frames.py):
- LLMTextFrame(TextFrame): "Text frame generated by LLM services" — los
  tokens en streaming que el LLM empuja aguas abajo hacia el TTS.
- LLMFullResponseStartFrame / LLMFullResponseEndFrame (ControlFrame):
  delimitan la respuesta completa del LLM.
- InterruptionFrame(SystemFrame): barge-in del usuario; registramos lo
  acumulado hasta el corte marcándolo como interrumpido.
"""

from pipecat.frames.frames import (
    Frame,
    InterruptionFrame,
    LLMFullResponseEndFrame,
    LLMFullResponseStartFrame,
    LLMTextFrame,
)
from pipecat.processors.frame_processor import FrameDirection, FrameProcessor

import events


class ConversationLog(FrameProcessor):
    """Acumula el texto del turno del asistente y lo registra al cerrarse.

    No modifica ni filtra nada: empuja SIEMPRE todos los frames tal cual.
    """

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self._parts: list[str] = []
        self._in_response = False

    def _flush(self, *, interrupted: bool = False) -> None:
        text = "".join(self._parts).strip()
        self._parts = []
        self._in_response = False
        if text:
            payload: dict = {"text": text}
            if interrupted:
                # El LLM lo generó, pero el TTS pudo no llegar a decirlo entero.
                payload["interrupted"] = True
            events.log_event("assistant_said", payload)

    async def process_frame(self, frame: Frame, direction: FrameDirection):
        await super().process_frame(frame, direction)

        if direction == FrameDirection.DOWNSTREAM:
            if isinstance(frame, LLMFullResponseStartFrame):
                self._parts = []
                self._in_response = True
            elif isinstance(frame, LLMTextFrame):
                if self._in_response and frame.text:
                    self._parts.append(frame.text)
            elif isinstance(frame, LLMFullResponseEndFrame):
                self._flush()

        if isinstance(frame, InterruptionFrame) and self._parts:
            self._flush(interrupted=True)

        await self.push_frame(frame, direction)
